apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-quickstarts
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/giofontana/OpenShift-Multi-Cluster-Management-Handbook.git'
    path: quarkus-getting-started/k8s/overlay/v2/
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
